#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "babyDuck2.y".
#

require 'racc/parser.rb'


class SemanticError < StandardError; end

class BabyDuck < Racc::Parser

module_eval(<<'...end babyDuck2.y/module_eval...', 'babyDuck2.y', 311)
def parse(str)
  # Initialize semantic analysis variables
  @symbol_tables = {}
  @current_scope = nil
  @current_function = nil
  @current_vars = []
  @current_var = nil
  @var_type = nil
  @calling_function = nil
  @current_param_count = 0

  @semantic_Cube = {
    'int' => {
      'int' => 'int',
      'float' => 'float',
      'string' => 'error'
    },
    'float' => {
      'int' => 'float',
      'float' => 'float',
      'string' => 'error'
    },
    'string' => {
      'int' => 'error',
      'float' => 'error',
      'string' => 'string'
    }
  }

  @q = []
  until str.empty?
    case str
    when /\A\s+/
      # Ignora los espacios en blanco
    when /\A(program|main|end|var|void|if|else|while|do|print|int|float)\b/
      # Palabras clave reservadas - devuelve el token como su propio nombre
      @q.push [$&, $&]
    when /\A[a-zA-Z][a-zA-Z0-9_]*/
      # Identificador
      @q.push [:ID, $&]
    when /\A[0-9]+\.[0-9]+/
      # Constante flotante
      @q.push [:CTE_FLOAT, $&.to_f]
    when /\A[0-9]+/
      # Constante entera
      @q.push [:CTE_INT, $&.to_i]
    when /\A\"[^\"]*\"/
      # Constante string (incluyendo las comillas)
      @q.push [:CTE_STRING, $&[1...-1]] # Eliminamos las comillas
    when /\A(==|!=|<=|>=|<|>)/o
      #operadores de comparación
      @q.push [$&, $&]
    when /\A.|\n/o
      # Cualquier otro carácter (operadores, paréntesis, etc.)
      s = $&
      @q.push [s, s]
    end
    str = $'
  end
  @q.push [false, '$end']
  do_parse
end

def next_token
  @q.shift
end

# Helper function to check if a variable exists in current scope or global scope
def variable_exists(var_name)
  # Check current scope first
  return true if @symbol_tables[@current_scope] && @symbol_tables[@current_scope][var_name]
  
  # Check global scope if we're not already in it
  return true if @current_scope != 'global' && @symbol_tables['global'][var_name]
  
  # Variable not found
  false
end

# Helper function to get variable type
def get_variable_type(var_name)
  # Check current scope first
  if @symbol_tables[@current_scope] && @symbol_tables[@current_scope][var_name]
    return @symbol_tables[@current_scope][var_name][:type]
  end
  
  # Check global scope if we're not already in it
  if @current_scope != 'global' && @symbol_tables['global'][var_name]
    return @symbol_tables['global'][var_name][:type]
  end
  
  # Variable not found
  nil
end

def get_variable_value(var_name)
  # Check current scope first
  if @symbol_tables[@current_scope] && @symbol_tables[@current_scope][var_name]
    return @symbol_tables[@current_scope][var_name][:value]
  end
  
  # Check global scope if we're not already in it
  if @current_scope != 'global' && @symbol_tables['global'][var_name]
    return @symbol_tables['global'][var_name][:value]
  end
  
  # Variable not found
  nil
end

def set_variable_value(var_name, value)
  # Check current scope first
  if @symbol_tables[@current_scope] && @symbol_tables[@current_scope][var_name]
    @symbol_tables[@current_scope][var_name][:value] = value
  end
  
  # Check global scope if we're not already in it
  if @current_scope != 'global' && @symbol_tables['global'][var_name]
    @symbol_tables['global'][var_name][:value] = value
  end
  
  # Variable not found
  nil
end

# Helper to print the symbol table (for debugging)
def print_symbol_tables
  puts "\n==== SYMBOL TABLES ===="
  @symbol_tables.each do |scope, vars|
    puts "SCOPE: #{scope}"
    vars.each do |var_name, details|
      puts "  #{var_name}: #{details}"
    end
    puts ""
  end
  puts "======================="
end

# Helper to evaluate expressions
def evaluate_expression_types(type1, type2)
  if @semantic_Cube[type1] && @semantic_Cube[type1][type2]
    return @semantic_Cube[type1][type2]
  end
  return 'error'
end

def evaluate_operation(left, op, right)
  puts "DEBUG: Evaluating operation: #{left} #{op} #{right}"
  case op
  when '+'
    return left + right
  when '-'
    return left - right
  when '*'
    return left * right
  when '/'
    return left / right
  when '>'
    return left > right ? 1 : 0
  when '<'
    return left < right ? 1 : 0
  when '!='
    return left != right ? 1 : 0
  end
end

...end babyDuck2.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    50,    50,    74,     3,    74,     4,    74,     5,   103,    74,
    92,    93,    94,    71,    72,    71,    72,    71,    72,     6,
    71,    72,     7,    74,    88,    11,    51,    51,    52,    52,
    54,    54,   105,   106,    71,    72,    74,   -70,    74,    15,
    74,   -70,    74,    18,    74,    88,    74,    71,    72,    71,
    72,    71,    72,    71,    72,    71,    72,    71,    72,    30,
    31,    30,    31,    71,    72,    99,   100,    19,    20,    21,
    22,    23,    28,    34,    35,    37,    38,    39,    18,    41,
    55,    28,    59,    61,    62,    63,    64,    65,    11,    18,
    34,    90,   107,   108,   109,   110,   112,   -77,   114,   118,
    34,   120,   121,   122,   123,   124,   126,    34,   130,    34,
   132,    15 ]

racc_action_check = [
    34,    44,    65,     0,    61,     1,    62,     3,    76,    63,
    69,    69,    69,    65,    65,    61,    61,    62,    62,     4,
    63,    63,     5,   123,    65,     8,    34,    44,    34,    44,
    34,    44,    76,    76,   123,   123,    64,    64,    74,     9,
    84,    84,    91,    11,    96,   123,    98,    64,    64,    74,
    74,    84,    84,    91,    91,    96,    96,    98,    98,    22,
    22,    38,    38,    70,    70,    73,    73,    12,    14,    15,
    17,    18,    20,    24,    25,    27,    28,    29,    32,    33,
    35,    37,    42,    50,    51,    52,    53,    54,    55,    58,
    66,    68,    78,    79,    80,    81,    85,    86,    89,   101,
   107,   108,   110,   112,   113,   114,   119,   120,   125,   126,
   127,   129 ]

racc_action_pointer = [
     1,     5,   nil,     4,    19,    18,   nil,   nil,    18,    23,
   nil,    40,    62,   nil,    56,    66,   nil,    62,    62,   nil,
    69,   nil,    49,   nil,    56,    61,   nil,    66,    68,    73,
   nil,   nil,    75,    73,    -3,    66,   nil,    78,    51,   nil,
   nil,   nil,    64,   nil,    -2,   nil,   nil,   nil,   nil,   nil,
    64,    72,    73,    74,    75,    81,   nil,   nil,    86,   nil,
   nil,    -8,    -6,    -3,    24,   -10,    73,   nil,    87,   -10,
    40,   nil,   nil,    40,    26,   nil,     5,   nil,    79,    80,
    85,    82,   nil,   nil,    28,    83,    88,   nil,   nil,    83,
   nil,    30,   nil,   nil,   nil,   nil,    32,   nil,    34,   nil,
   nil,    86,   nil,   nil,   nil,   nil,   nil,    83,    69,   nil,
    98,   nil,    99,    95,   101,   nil,   nil,   nil,   nil,    76,
    90,   nil,   nil,    11,   nil,   104,    92,   106,   nil,    95,
   nil,   nil,   nil,   nil ]

racc_action_default = [
   -81,   -81,    -1,   -81,   -81,   -81,   134,    -2,    -6,   -17,
    -5,   -10,   -81,   -16,   -81,   -81,    -7,   -81,   -11,    -3,
   -22,   -20,   -81,   -12,   -81,   -81,   -21,   -26,   -81,   -81,
   -14,   -15,   -81,   -81,   -29,   -81,   -23,   -81,   -81,    -8,
   -13,    -4,   -81,   -28,   -29,   -32,   -33,   -34,   -35,   -36,
   -68,   -81,   -81,   -81,   -81,    -6,   -25,   -24,   -10,   -27,
   -31,   -58,   -58,   -58,   -58,   -58,   -81,    -9,   -81,   -39,
   -46,   -47,   -48,   -51,   -58,   -55,   -81,   -57,   -81,   -81,
   -38,   -81,   -69,   -71,   -58,   -81,   -76,   -79,   -80,   -81,
   -37,   -58,   -41,   -42,   -43,   -44,   -58,   -49,   -58,   -52,
   -53,   -81,   -56,   -59,   -60,   -61,   -62,   -81,   -81,   -74,
   -81,   -72,   -81,   -81,   -81,   -40,   -45,   -50,   -54,   -65,
   -81,   -67,   -75,   -58,   -18,   -81,   -81,   -81,   -78,   -17,
   -63,   -64,   -66,   -19 ]

racc_goto_table = [
    12,    33,    68,    78,    79,    85,    87,     9,    16,    81,
    26,    42,    29,   115,     1,   101,     2,     8,   116,    24,
    40,    60,    58,    32,    25,   129,    36,    56,    57,   111,
    91,   117,    95,    96,    97,    98,   102,   104,   125,   113,
   nil,   nil,   nil,    89,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    66,    67,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   128,    87,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   119,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   127,   nil,   nil,
   nil,   nil,   nil,   131,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   133 ]

racc_goto_check = [
     4,     5,    29,    29,    29,    48,    29,     3,     9,    45,
    18,    21,    11,    31,     1,    29,     2,     6,    31,     7,
    10,    21,    12,    13,    16,    17,    20,    18,    11,    45,
    32,    33,    34,    35,    37,    38,    41,    42,    43,    50,
   nil,   nil,   nil,     5,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     3,     9,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    48,    29,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     5,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,   nil,   nil,
   nil,   nil,   nil,     5,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     4 ]

racc_goto_pointer = [
   nil,    14,    16,    -1,    -9,   -23,    10,     0,   nil,    -3,
   -12,   -10,   -17,     0,   nil,   nil,     4,   -99,   -10,   nil,
    -1,   -23,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   -59,
   nil,   -78,   -39,   -67,   -38,   -37,   nil,   -39,   -38,   nil,
   nil,   -40,   -39,   -81,   nil,   -55,   nil,   nil,   -60,   nil,
   -47 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    10,   nil,
    17,   nil,   nil,   nil,    13,    14,   nil,   nil,   nil,    27,
   nil,   nil,    43,    44,    45,    46,    47,    48,    49,    80,
    83,    69,   nil,    70,   nil,    77,    73,   nil,   nil,    75,
    76,   nil,   nil,   nil,    53,   nil,    82,    84,   nil,    86,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 36, :_reduce_none,
  0, 41, :_reduce_2,
  0, 42, :_reduce_3,
  10, 37, :_reduce_4,
  1, 38, :_reduce_none,
  0, 38, :_reduce_none,
  2, 43, :_reduce_none,
  0, 47, :_reduce_8,
  6, 44, :_reduce_none,
  0, 44, :_reduce_none,
  1, 45, :_reduce_11,
  0, 48, :_reduce_12,
  4, 45, :_reduce_13,
  1, 46, :_reduce_14,
  1, 46, :_reduce_15,
  1, 39, :_reduce_none,
  0, 39, :_reduce_none,
  0, 52, :_reduce_18,
  11, 49, :_reduce_none,
  2, 50, :_reduce_20,
  1, 51, :_reduce_none,
  0, 51, :_reduce_none,
  2, 53, :_reduce_none,
  3, 54, :_reduce_24,
  2, 55, :_reduce_none,
  0, 55, :_reduce_none,
  3, 40, :_reduce_none,
  1, 56, :_reduce_none,
  0, 56, :_reduce_none,
  1, 57, :_reduce_none,
  2, 57, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  1, 58, :_reduce_none,
  4, 59, :_reduce_37,
  1, 65, :_reduce_38,
  1, 64, :_reduce_39,
  3, 64, :_reduce_40,
  1, 67, :_reduce_41,
  1, 67, :_reduce_42,
  1, 67, :_reduce_43,
  2, 66, :_reduce_44,
  2, 69, :_reduce_45,
  0, 69, :_reduce_46,
  1, 70, :_reduce_47,
  1, 70, :_reduce_48,
  2, 68, :_reduce_49,
  2, 72, :_reduce_50,
  0, 72, :_reduce_51,
  1, 73, :_reduce_52,
  1, 73, :_reduce_53,
  3, 71, :_reduce_54,
  1, 71, :_reduce_55,
  2, 74, :_reduce_56,
  1, 75, :_reduce_57,
  0, 75, :_reduce_58,
  1, 76, :_reduce_59,
  1, 76, :_reduce_60,
  1, 77, :_reduce_61,
  1, 77, :_reduce_62,
  7, 60, :_reduce_none,
  2, 78, :_reduce_none,
  0, 78, :_reduce_none,
  7, 61, :_reduce_none,
  5, 62, :_reduce_67,
  1, 79, :_reduce_68,
  1, 80, :_reduce_none,
  0, 80, :_reduce_none,
  1, 81, :_reduce_none,
  2, 81, :_reduce_none,
  1, 65, :_reduce_73,
  2, 82, :_reduce_74,
  5, 63, :_reduce_75,
  1, 83, :_reduce_76,
  0, 85, :_reduce_77,
  4, 83, :_reduce_none,
  1, 84, :_reduce_79,
  1, 84, :_reduce_80 ]

racc_reduce_n = 81

racc_shift_n = 134

racc_token_table = {
  false => 0,
  :error => 1,
  "program" => 2,
  :ID => 3,
  ";" => 4,
  "main" => 5,
  "end" => 6,
  "var" => 7,
  ":" => 8,
  "," => 9,
  "int" => 10,
  "float" => 11,
  "(" => 12,
  ")" => 13,
  "[" => 14,
  "]" => 15,
  "void" => 16,
  "{" => 17,
  "}" => 18,
  "=" => 19,
  ">" => 20,
  "<" => 21,
  "!=" => 22,
  "+" => 23,
  "-" => 24,
  "*" => 25,
  "/" => 26,
  :CTE_INT => 27,
  :CTE_FLOAT => 28,
  "if" => 29,
  "else" => 30,
  "while" => 31,
  "do" => 32,
  "print" => 33,
  :CTE_STRING => 34 }

racc_nt_base = 35

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"program\"",
  "ID",
  "\";\"",
  "\"main\"",
  "\"end\"",
  "\"var\"",
  "\":\"",
  "\",\"",
  "\"int\"",
  "\"float\"",
  "\"(\"",
  "\")\"",
  "\"[\"",
  "\"]\"",
  "\"void\"",
  "\"{\"",
  "\"}\"",
  "\"=\"",
  "\">\"",
  "\"<\"",
  "\"!=\"",
  "\"+\"",
  "\"-\"",
  "\"*\"",
  "\"/\"",
  "CTE_INT",
  "CTE_FLOAT",
  "\"if\"",
  "\"else\"",
  "\"while\"",
  "\"do\"",
  "\"print\"",
  "CTE_STRING",
  "$start",
  "target",
  "program",
  "vars",
  "funcs",
  "body",
  "@1",
  "@2",
  "varsdec",
  "varlist",
  "varsids",
  "type",
  "@3",
  "@4",
  "funcsdec",
  "func_header",
  "funcvars",
  "@5",
  "funcvarsdec",
  "param_declaration",
  "funcvarsdeclist",
  "statement",
  "statedec",
  "statevalues",
  "assign",
  "condition",
  "cycle",
  "fcall",
  "printstat",
  "expression",
  "single_param",
  "exp",
  "operator",
  "term",
  "termlist",
  "termop",
  "factor",
  "factorlist",
  "factorop",
  "factorids",
  "expop",
  "expids",
  "const",
  "optionalelse",
  "function_id",
  "funccallexp",
  "funcexplist",
  "single_param_comma",
  "printexplist",
  "printvalue",
  "@6" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'babyDuck2.y', 13)
  def _reduce_2(val, _values, result)
          # Initialize the symbol tables
      @current_scope = 'global'
      @symbol_tables = { 'global' => {} }
      @current_function = nil

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 19)
  def _reduce_3(val, _values, result)
          @current_scope = 'main'
      @symbol_tables['main'] = {}

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 23)
  def _reduce_4(val, _values, result)
          puts "Codigo compilado correctamente"
      result = val[1]

    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

module_eval(<<'.,.,', 'babyDuck2.y', 31)
  def _reduce_8(val, _values, result)
          # Add all variables of this type to the current scope
      puts "Received type: #{@var_type}"
      @current_vars.each do |var_name|
        if @symbol_tables[@current_scope][var_name]
          raise SemanticError, "Variable decalration: Variable '#{var_name}' already declared in scope '#{@current_scope}'"
        else
          @symbol_tables[@current_scope][var_name] = {type: @var_type, value: nil}
          puts "Added variable '#{var_name}' of type '#{@var_type}' to scope '#{@current_scope}'"
        end
      end

    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

module_eval(<<'.,.,', 'babyDuck2.y', 44)
  def _reduce_11(val, _values, result)
          @current_vars = [val[0]]

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 47)
  def _reduce_12(val, _values, result)
          @current_vars = [val[0]]

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 50)
  def _reduce_13(val, _values, result)
          @current_vars.unshift(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 53)
  def _reduce_14(val, _values, result)
        @var_type = 'int'
    result = 'int'

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 57)
  def _reduce_15(val, _values, result)
        @var_type = 'float'
    result = 'float'

    result
  end
.,.,

# reduce 16 omitted

# reduce 17 omitted

module_eval(<<'.,.,', 'babyDuck2.y', 64)
  def _reduce_18(val, _values, result)
        # Return to global scope after function definition
    @current_scope = 'global'
    @current_function = nil

    result
  end
.,.,

# reduce 19 omitted

module_eval(<<'.,.,', 'babyDuck2.y', 71)
  def _reduce_20(val, _values, result)
        # Store function name
    @current_function = val[1]
    @current_scope = val[1]
    @symbol_tables[@current_scope] = {}
    puts "Created new function scope: #{@current_scope}"
    
    # Return the function name for potential use in parent rule
    result = val[1]

    result
  end
.,.,

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

module_eval(<<'.,.,', 'babyDuck2.y', 85)
  def _reduce_24(val, _values, result)
        var_name = val[0]
    
    if @symbol_tables[@current_scope][var_name]
      raise SemanticError, "Parameter declaration: Parameter '#{var_name}' already declared in function '#{@current_scope}'"
    else
      @symbol_tables[@current_scope][var_name] = {type: val[2], is_param: true}
      puts "Added parameter '#{var_name}' of type '#{val[2]}' to function '#{@current_scope}'"
    end
    
    # Return the parameter name for potential use in parent rule
    result = var_name

    result
  end
.,.,

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

module_eval(<<'.,.,', 'babyDuck2.y', 110)
  def _reduce_37(val, _values, result)
          puts "Assigned value: #{val[2]} to variable: #{val[0]}"
      # Check if variable exists in current scope or global scope
      var_name = val[0]
      if !variable_exists(var_name)
        raise SemanticError, "Assignment: Variable '#{var_name}' not declared before use"
      end
      if val[2][:type2] != nil
        puts "assignment with 2 operands"
        resultingType = evaluate_expression_types(val[2][:type1], val[2][:type2])
        # Check if the types are compatible
        if resultingType == 'error'
          raise SemanticError, "Assignment: Type mismatch in assignment to variable '#{var_name}'"
        end
        if get_variable_type(var_name) != resultingType
          raise SemanticError, "Assignment: Type mismatch in assignment to variable '#{var_name}'"
        end
        # Set the variable value
        set_variable_value(var_name, evaluate_operation(val[2][:value1], val[2][:operation], val[2][:value2]))
      else
        puts "assignment with 1 operand"
        resultingType = val[2][:type]
        # Check if the types are compatible
        if evaluate_expression_types(get_variable_type(var_name), resultingType) == 'error'
          raise SemanticError, "Assignment: Type mismatch in assignment to variable '#{var_name}'"
        end
        # Set the variable value
        set_variable_value(var_name, val[2][:value])
      end

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 141)
  def _reduce_38(val, _values, result)
        @current_param_count += 1
    result = val[0]  # Return the expression value

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 147)
  def _reduce_39(val, _values, result)
        result = val[0]  # Pass up the exp value

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 150)
  def _reduce_40(val, _values, result)
        left = val[0]
    op = val[1]
    right = val[2]
    puts "DEBUG: Expression with operator: left: #{left} op: #{op} right: #{right}"
    # Here you might evaluate the expression or build a node
    result = { left: left, operator: op, right: right }

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 158)
  def _reduce_41(val, _values, result)
     result = '>'
    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 159)
  def _reduce_42(val, _values, result)
     result = '<'
    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 160)
  def _reduce_43(val, _values, result)
     result = '!='
    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 163)
  def _reduce_44(val, _values, result)
        if val[1].nil? || val[1].empty?  # No operations in termlist
      result = val[0]  # Just pass up the term value
    else
      # Handle operations from termlist
      term = val[0]
      ops = val[1]
      puts "DEBUG: Exp with termlist: #{term} #{ops}"
      result = { name1: term[:name], type1: term[:type], value1: term[:value], operation: ops[:operator], name2: ops[:name], type2: ops[:type], value2: ops[:value] }
    end

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 175)
  def _reduce_45(val, _values, result)
        result = { operator: val[0], name: val[1][:name], type: val[1][:type], value: val[1][:value] }

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 178)
  def _reduce_46(val, _values, result)
        result = nil  # No operations

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 181)
  def _reduce_47(val, _values, result)
     result = '+'
    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 182)
  def _reduce_48(val, _values, result)
     result = '-'
    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 185)
  def _reduce_49(val, _values, result)
        if val[1].nil? || val[1].empty?  # No operations in factorlist
      result = val[0]  # Just pass up the factor value
    else
      # Handle operations from factorlist
      factor = val[0]
      ops = val[1]
      puts "DEBUG: Term with factorlist: #{factor} #{ops}"
      result = { name1: factor[:name], type1: factor[:type], value1: factor[:value], operation: ops[:operator], name2: ops[:name], type2: ops[:type], value2: ops[:value] }
    end

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 197)
  def _reduce_50(val, _values, result)
        result = { operator: val[0], name: val[1][:name], type: val[1][:type], value: val[1][:value] }

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 200)
  def _reduce_51(val, _values, result)
        result = nil  # No operations

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 203)
  def _reduce_52(val, _values, result)
     result = '*'
    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 204)
  def _reduce_53(val, _values, result)
     result = '/'
    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 207)
  def _reduce_54(val, _values, result)
        result = val[1]  # Return the expression inside parentheses

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 210)
  def _reduce_55(val, _values, result)
        result = val[0]  # Pass up the factorids value

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 214)
  def _reduce_56(val, _values, result)
        if val[0].nil? || val[0].empty?  # No operator
      result = val[1]  # Just pass up the expids value
    else
      # Apply unary operator
      op = val[0]
      value = val[1]
      puts "DEBUG: Factorids with expop: #{op} #{value}"
      result = { operator: op, value: value }
    end

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 226)
  def _reduce_57(val, _values, result)
        result = val[0]  # Pass up the termop value

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 229)
  def _reduce_58(val, _values, result)
        result = nil  # No operator

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 233)
  def _reduce_59(val, _values, result)
        # Check if variable exists when used in expression
    var_name = val[0]
    if !variable_exists(var_name)
      raise SemanticError, "Expression: Variable '#{var_name}' not declared before use"
    end
    var_type = get_variable_type(var_name)
    var_value = get_variable_value(var_name)
    result = { name: var_name, type: var_type, value: var_value }

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 243)
  def _reduce_60(val, _values, result)
        result = val[0]  # Pass up the const value

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 247)
  def _reduce_61(val, _values, result)
        result = {name: 'int const', value: val[0], type: 'int' }

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 250)
  def _reduce_62(val, _values, result)
        result = { name: 'float const', value: val[0], type: 'float' }

    result
  end
.,.,

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

module_eval(<<'.,.,', 'babyDuck2.y', 262)
  def _reduce_67(val, _values, result)
        # Reset function calling state
    @calling_function = nil
    result = val[0]  # Return the function ID from function_id rule

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 268)
  def _reduce_68(val, _values, result)
        func_name = val[0]
    
    # Check if function exists
    if !@symbol_tables[func_name]
      raise SemanticError, "Function call: Function '#{func_name}' not declared before use"
    end
    
    # Set up function call state
    @current_param_count = 0
    @calling_function = func_name
    
    # Return the function name for use in parent rule
    result = func_name

    result
  end
.,.,

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

module_eval(<<'.,.,', 'babyDuck2.y', 287)
  def _reduce_73(val, _values, result)
        @current_param_count += 1
    result = val[0]  # Return the expression value

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 292)
  def _reduce_74(val, _values, result)
        @current_param_count += 1
    result = val[0]  # Return the expression value

    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 297)
  def _reduce_75(val, _values, result)
     result = val[2]; puts "printed #{val[2]}"
    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 298)
  def _reduce_76(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 298)
  def _reduce_77(val, _values, result)
     result = val[0]
    result
  end
.,.,

# reduce 78 omitted

module_eval(<<'.,.,', 'babyDuck2.y', 299)
  def _reduce_79(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'babyDuck2.y', 299)
  def _reduce_80(val, _values, result)
     result = val[0]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class BabyDuck


if $0 == __FILE__
  parser = BabyDuck.new
  # Código para probar tu parser

  if ARGV[0]
    input = File.read(ARGV[0])
    begin
      result = parser.parse(input)
      # Print symbol tables for debugging
      parser.print_symbol_tables
      puts "Análisis exitoso: #{result}"
    rescue SemanticError => e
      puts "Error: #{e.message}"
    end
  end
end
