#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "babyDuck.y".
#

require 'racc/parser.rb'



# variables dictionary

#

class BabyDuck < Racc::Parser

module_eval(<<'...end babyDuck.y/module_eval...', 'babyDuck.y', 85)
def parse(str)
  @q = []
  until str.empty?
    case str
    when /\A\s+/
      # Ignora los espacios en blanco
    when /\A(program|main|end|var|void|if|else|while|do|print|int|float)\b/
      # Palabras clave reservadas - devuelve el token como su propio nombre
      @q.push [$&, $&]
    when /\A[a-zA-Z][a-zA-Z0-9_]*/
      # Identificador
      @q.push [:ID, $&]
    when /\A[0-9]+\.[0-9]+/
      # Constante flotante
      @q.push [:CTE_FLOAT, $&.to_f]
    when /\A[0-9]+/
      # Constante entera
      @q.push [:CTE_INT, $&.to_i]
    when /\A\"[^\"]*\"/
      # Constante string (incluyendo las comillas)
      @q.push [:CTE_STRING, $&[1...-1]] # Eliminamos las comillas
    when /\A.|\n/o
      # Cualquier otro carácter (operadores, paréntesis, etc.)
      s = $&
      @q.push [s, s]
    end
    str = $'
  end
  @q.push [false, '$end']
  do_parse
end

def next_token
  @q.shift
end

...end babyDuck.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    37,    37,    61,     3,    61,     4,    61,     5,    89,    61,
   -61,    61,    58,    59,    58,    59,    58,    59,     6,    58,
    59,    58,    59,    73,    61,    73,    38,    38,    39,    39,
    40,    40,    91,    92,    58,    59,    61,    48,    61,     7,
    61,    10,    61,    47,    61,   -61,    58,    59,    58,    59,
    58,    59,    58,    59,    58,    59,    78,    79,    80,    25,
    26,    25,    26,    58,    59,    85,    86,    13,    16,    17,
    18,    19,    20,    22,    23,    16,    28,    43,    44,    45,
    49,    50,    51,    52,    53,    16,    74,    76,    93,    94,
    95,    96,    97,    98,    10,   101,   105,   106,    22,   109,
   110,    22,    43,   115,    22,   117,   118,    22,   120,   121,
    13 ]

racc_action_check = [
    22,    31,    51,     0,    98,     1,    47,     3,    63,    48,
    48,    49,    51,    51,    98,    98,    47,    47,     4,    48,
    48,    49,    49,    51,    50,    98,    22,    31,    22,    31,
    22,    31,    63,    63,    50,    50,    61,    37,    77,     5,
    82,     7,    84,    37,    94,    94,    61,    61,    77,    77,
    82,    82,    84,    84,    94,    94,    56,    56,    56,    19,
    19,    53,    53,    57,    57,    60,    60,     8,    10,    11,
    13,    15,    16,    17,    18,    20,    21,    23,    24,    29,
    38,    39,    40,    41,    43,    44,    52,    55,    65,    67,
    68,    69,    70,    71,    74,    75,    87,    93,    95,    96,
    97,    99,   101,   108,   109,   112,   114,   115,   116,   117,
   121 ]

racc_action_pointer = [
     1,     5,   nil,     4,    18,    35,   nil,    34,    55,   nil,
    65,    64,   nil,    67,   nil,    63,    63,    56,    61,    49,
    72,    70,    -3,    74,    74,   nil,   nil,   nil,   nil,    61,
   nil,    -2,   nil,   nil,   nil,   nil,   nil,    24,    67,    68,
    69,    69,   nil,    76,    82,   nil,   nil,    -7,    -4,    -2,
    11,   -11,    71,    51,   nil,    83,    36,    40,   nil,   nil,
    40,    23,   nil,     5,   nil,    74,   nil,    80,    76,    77,
    78,    84,   nil,   nil,    87,    86,   nil,    25,   nil,   nil,
   nil,   nil,    27,   nil,    29,   nil,   nil,    82,   nil,   nil,
   nil,   nil,   nil,    93,    31,    81,    67,    96,    -9,    84,
   nil,    99,   nil,   nil,   nil,   nil,   nil,   nil,    73,    87,
   nil,   nil,    89,   nil,   102,    90,   104,   105,   nil,   nil,
   nil,    98,   nil ]

racc_action_default = [
   -69,   -69,    -1,   -69,   -69,   -69,   123,    -4,   -13,    -3,
    -7,   -69,   -12,   -69,    -5,   -69,    -8,   -69,   -69,   -69,
   -69,   -69,   -22,   -16,   -69,   -10,   -11,    -9,    -2,   -69,
   -21,   -22,   -25,   -26,   -27,   -28,   -29,   -69,   -69,   -69,
   -69,   -69,   -15,   -69,    -7,   -20,   -24,   -50,   -50,   -50,
   -50,   -50,   -69,   -69,    -6,   -69,   -31,   -38,   -39,   -40,
   -43,   -50,   -47,   -69,   -49,   -69,   -60,   -62,   -69,   -69,
   -69,   -65,   -67,   -68,    -4,   -19,   -30,   -50,   -33,   -34,
   -35,   -36,   -50,   -41,   -50,   -44,   -45,   -69,   -48,   -51,
   -52,   -53,   -54,   -69,   -50,   -69,   -69,   -69,   -50,   -69,
   -17,   -69,   -32,   -37,   -42,   -46,   -59,   -63,   -57,   -69,
   -64,   -66,   -69,   -18,   -69,   -69,   -69,   -69,   -55,   -56,
   -58,   -13,   -14 ]

racc_goto_table = [
    11,    21,    42,     8,    55,    70,    68,    69,    72,    14,
    65,    24,    29,     1,   102,     2,    27,    41,    87,   103,
   100,    46,    77,   104,    81,    82,    83,    84,    88,    90,
   114,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    54,   nil,    75,   nil,   nil,   nil,   nil,
   nil,   nil,   111,   nil,   nil,    72,   107,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    99,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   108,
   113,   nil,   nil,   112,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   116,   nil,   nil,   nil,   nil,   nil,   119,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   122 ]

racc_goto_check = [
     4,     5,    12,     3,    22,    38,    22,    22,    22,     7,
    36,     9,    14,     1,    23,     2,     8,    11,    22,    23,
    13,    14,    24,    25,    26,    27,    29,    30,    33,    34,
    35,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     7,   nil,     9,   nil,   nil,   nil,   nil,
   nil,   nil,    38,   nil,   nil,    22,    36,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,
    12,   nil,   nil,     5,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     5,   nil,   nil,   nil,   nil,   nil,     5,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     4 ]

racc_goto_pointer = [
   nil,    13,    15,    -4,    -8,   -16,   nil,    -1,    -4,    -8,
   nil,    -6,   -21,   -55,   -10,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   -43,   -63,   -34,   -61,   -33,   -32,   nil,   -34,
   -33,   nil,   nil,   -35,   -34,   -78,   -38,   nil,   -46,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,     9,   nil,    15,   nil,
    12,   nil,   nil,   nil,   nil,    30,    31,    32,    33,    34,
    35,    36,    67,    56,   nil,    57,   nil,    64,    60,   nil,
   nil,    62,    63,   nil,   nil,   nil,   nil,    66,   nil,    71 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 36, :_reduce_none,
  8, 37, :_reduce_2,
  1, 38, :_reduce_none,
  0, 38, :_reduce_none,
  2, 41, :_reduce_none,
  5, 42, :_reduce_none,
  0, 42, :_reduce_none,
  1, 43, :_reduce_none,
  3, 43, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 39, :_reduce_none,
  0, 39, :_reduce_none,
  11, 45, :_reduce_none,
  1, 46, :_reduce_none,
  0, 46, :_reduce_none,
  4, 47, :_reduce_none,
  2, 48, :_reduce_none,
  0, 48, :_reduce_none,
  3, 40, :_reduce_none,
  1, 49, :_reduce_none,
  0, 49, :_reduce_none,
  1, 50, :_reduce_none,
  2, 50, :_reduce_none,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  4, 52, :_reduce_none,
  1, 57, :_reduce_none,
  3, 57, :_reduce_none,
  1, 59, :_reduce_none,
  1, 59, :_reduce_none,
  1, 59, :_reduce_none,
  2, 58, :_reduce_none,
  2, 61, :_reduce_none,
  0, 61, :_reduce_none,
  1, 62, :_reduce_none,
  1, 62, :_reduce_none,
  2, 60, :_reduce_none,
  2, 64, :_reduce_none,
  0, 64, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  3, 63, :_reduce_none,
  1, 63, :_reduce_none,
  2, 66, :_reduce_none,
  1, 67, :_reduce_none,
  0, 67, :_reduce_none,
  1, 68, :_reduce_none,
  1, 68, :_reduce_none,
  1, 69, :_reduce_none,
  1, 69, :_reduce_none,
  7, 53, :_reduce_none,
  2, 70, :_reduce_none,
  0, 70, :_reduce_none,
  7, 54, :_reduce_none,
  5, 55, :_reduce_none,
  1, 71, :_reduce_none,
  0, 71, :_reduce_none,
  1, 72, :_reduce_none,
  3, 72, :_reduce_none,
  5, 56, :_reduce_none,
  1, 73, :_reduce_none,
  3, 73, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none ]

racc_reduce_n = 69

racc_shift_n = 123

racc_token_table = {
  false => 0,
  :error => 1,
  "program" => 2,
  :ID => 3,
  ";" => 4,
  "main" => 5,
  "end" => 6,
  "var" => 7,
  ":" => 8,
  "," => 9,
  "int" => 10,
  "float" => 11,
  "void" => 12,
  "(" => 13,
  ")" => 14,
  "[" => 15,
  "]" => 16,
  "{" => 17,
  "}" => 18,
  "=" => 19,
  ">" => 20,
  "<" => 21,
  "!=" => 22,
  "+" => 23,
  "-" => 24,
  "*" => 25,
  "/" => 26,
  :CTE_INT => 27,
  :CTE_FLOAT => 28,
  "if" => 29,
  "else" => 30,
  "while" => 31,
  "do" => 32,
  "print" => 33,
  :CTE_STRING => 34 }

racc_nt_base = 35

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"program\"",
  "ID",
  "\";\"",
  "\"main\"",
  "\"end\"",
  "\"var\"",
  "\":\"",
  "\",\"",
  "\"int\"",
  "\"float\"",
  "\"void\"",
  "\"(\"",
  "\")\"",
  "\"[\"",
  "\"]\"",
  "\"{\"",
  "\"}\"",
  "\"=\"",
  "\">\"",
  "\"<\"",
  "\"!=\"",
  "\"+\"",
  "\"-\"",
  "\"*\"",
  "\"/\"",
  "CTE_INT",
  "CTE_FLOAT",
  "\"if\"",
  "\"else\"",
  "\"while\"",
  "\"do\"",
  "\"print\"",
  "CTE_STRING",
  "$start",
  "target",
  "program",
  "vars",
  "funcs",
  "body",
  "varsdec",
  "varlist",
  "varsids",
  "type",
  "funcsdec",
  "funcvars",
  "funcvarsdec",
  "funcvarsdeclist",
  "statement",
  "statedec",
  "statevalues",
  "assign",
  "condition",
  "cycle",
  "fcall",
  "printstat",
  "expression",
  "exp",
  "operator",
  "term",
  "termlist",
  "termop",
  "factor",
  "factorlist",
  "factorop",
  "factorids",
  "expop",
  "expids",
  "const",
  "optionalelse",
  "funccallexp",
  "funcexplist",
  "printexplist",
  "printvalue" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'babyDuck.y', 13)
  def _reduce_2(val, _values, result)
        puts "Codigo compilado correctamente"
    result = val[1]

    result
  end
.,.,

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class BabyDuck


if $0 == __FILE__
  parser = BabyDuck.new
  # Código para probar tu parser

  if ARGV[0]
    input = File.read(ARGV[0])
    begin
      result = parser.parse(input)
      puts "Análisis exitoso: #{result}"
    rescue => e
      puts "Error: #{e.message}"
    end
  end
end
